---
- name: setup of jenkins and required softwares
  hosts: jenkins
  tasks:
    - name: install required s/w
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk,b: yes}
        - {a: git,b: no}
        - {a: maven,b: no}
    - name: download jenkins.war file
      get_url:
        url: https://get.jenkins.io/war-stable/2.387.3/jenkins.war
        dest: /home/ubuntu
- name: install tomcat9 and required s/w's
  hosts: servers
  tasks:
    - name: install required s/w's
      apt:
        name: "{{item.c}}"
        state: present
        update_cache: "{{item.d}}"
      with_items:
        - {c: tomcat9,d: yes}
        - {c: tomcat9-admin,d: no}
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: restart tomcat9
  handlers:
    - name: restart tomcat9
      service:   
        name: tomcat9
        state: restarted
... 



