---
- name: check if the file has execute permissions if so delete it
  hosts: all
  tasks:
    - name: check for file1 
      stat: 
        path: /tmp/file1
      register: a
    - name: display output of the above modules
      debug:
        var: a
    - name: delete file if it is not executable
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true     
