---
- name: implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation
    - name: create user
      user:
        name: anu
        password: intelliqit
      tags: user_creation
    - name: copy the password file
      copy:
         src: /etc/passwd
         dest: /tmp
...    

